name: classroom_abm
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - mesa
  - numpy
  - pandas
  - scipy=1.5.2
  # mlm dependencies
  - pip
  - pip:
    - -r file:pip-requirements.txt
  # dev dependencies
  - black
  - conda-lock
  - pre_commit
