name: classroom_abm
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - click
  - mesa
  - numpy
  - pandas
  - scipy=1.5.2
  # dev dependencies
  - black=20.8b1
  - conda-lock
  - pre_commit
  - pytest
  - seaborn
  - smt
