name: classroom_abm
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - mesa
  - numpy
  - pandas
  - scipy
  # mlm dependencies
  - rpy2
  # dev dependencies
  - black
  - conda-lock
  - pre_commit
