import os

import pandas as pd
import seaborn as sns


def plot_correlations(input_filename, output_filename=None):
    if output_filename is None:
        output_filename = os.path.join(
            os.path.dirname(input_filename), "correlations.png"
        )

    df = pd.read_csv(input_filename)
    y_vars = ["mean_squared_error"]

    # Set x_vars to parameter columns (exclude mse, test_id, etc)
    if input_filename.endswith("best_mses.csv"):
        # best_mses files generated by merge_best_results have MSE, directory
        # and test_id as last columns
        x_vars = list(df.columns.values)[0:-3]
    else:
        # other CSVs e.g. lowest_to_highest_mses have test_id at the start,
        # MSE at the end
        x_vars = list(df.columns.values)[1:-1]

    pp = sns.pairplot(data=df, kind="reg", y_vars=y_vars, x_vars=x_vars, diag_kind=None)
    pp.savefig(output_filename)
