# Worflow to test we can load our conda lock environments on win, macOS, and ubuntu

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  conda-lock-ci:
    name: Test conda lock
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            lock-file: "conda_locks/conda-linux-64.lock"
          - os: "macos-latest"
            lock-file: "conda_locks/conda-osx-64.lock"
          - os: "windows-latest"
            lock-file: "conda_locks/conda-win-64.lock"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          activate-environment: explicit-env
          environment-file: ${{ matrix.lock-file }}
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

  multilevel-analysis:
    name: Test multilevel analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      MLNSCRIPT_PATH: /usr/bin/mlnscript
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"

    steps:
      - uses: actions/checkout@v2
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          activate-environment: classroom_abm
          environment-file: conda_locks/conda-linux-64.lock
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.3'
      - name: Query R dependencies
        run: |
          install.packages('remotes')
          depends_path <- file.path(Sys.getenv('GITHUB_WORKSPACE'), ".github", "depends.Rds")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), depends_path, version = 2)
          r_version_path <- file.path(Sys.getenv('GITHUB_WORKSPACE'), ".github", "R-version")
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), r_version_path)
        shell: Rscript {0}
        working-directory: multilevel_analysis/R/classroommlm
      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      - name: Install system dependencies for R packages
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
      - name: Install R dependencies
        run: |
          remotes::install_cran(c("renv", "rcmdcheck")
        shell: Rscript {0}
      - name: Install MLwiN
        run: ./setup_mlwin.sh
        env:
          MLWIN_SHARE_URL: ${{ secrets.MLWIN_SHARE_URL }}
          MLWIN_DOWNLOAD_URL: ${{ secrets.MLWIN_DOWNLOAD_URL }}
      - name: Check classroommlm R package
        run: |
          options(crayon.enabled = TRUE)
          remotes::install_deps(dependencies = TRUE)
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")
        shell: Rscript {0}
        working-directory: multilevel_analysis/R/classroommlm
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
      - name: Run multilevel analysis
        run: |
          cd multilevel_analysis
          python multilevel_analysis.py
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r-results
          path: check
